
services:
  # web:
  #   build: .
  #   command: python manage.py runserver
  #   environment:
  #     - DEBUG=True
  #     - SECRET_KEY=secret
  #     # - ALLOWED_HOSTS=your_host
  #     - DATABASE_URL=postgres://mahim:testpass123@db:5432/local_db

  #   ports:
  #     - 8000:8000
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - db

  db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: local_db
      POSTGRES_USER: mahim
      POSTGRES_PASSWORD: testpass123
    volumes:
      - postgres_ecommerce_django_data:/var/lib/postgresql/data
  
  # adminer:
  #   image: adminer
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - db
  # pgadmin:
  #   image: dpage/pgadmin4
  #   ports:
  #     - "8000:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL:
    
volumes:
  postgres_ecommerce_django_data: