# Generated by Django 5.1.4 on 2025-07-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
